# deploy.yml content
- name: Deploy Kubernetes Manifests to AKS
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        src: k8s/deployment.yaml 
        # REMOVED: kubeconfig: ~/.kube/config

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        src: k8s/service.yaml 
        # REMOVED: kubeconfig: ~/.kube/config
