apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: default # <-- ADD THIS LINE
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        # IMAGE PLACEHOLDER: This will be dynamically replaced by the CI/CD pipeline
        image: <ACR_LOGIN_SERVER>/my-web-app:latest 
        ports:
        - containerPort: 5000
