apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default # <-- ADD THIS LINE
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 5000 
  selector:
    app: webapp
